### ISSUE TITLE
Periodic transform

### ISSUE THREAD

**Issue by glennmoy** [invenia/Transforms.jl#2]
A transform that applies a periodic function to the data with arguments
* `f` - the periodic function to apply
* `period` - the period of the function `f`
* `phase_shift` - an optional phase shift to be applied to the function argument 

Note that `phase_shift` is not strictly necessary for this function from a feature engineering perspective but may be required for debugging purposes and/or comparison against our current use of this function.

MWE
```julia
x = 1:1000

# period/phase could also just be positional args
periodic = Periodic(cos, period=5, phase_shift=2)

Transforms.apply!(x, periodic)
```

**Comment by bencottier** [comment]
> Note that phase_shift is not strictly necessary for this function from a feature engineering perspective but may be required for debugging purposes and/or comparison against our current use of this function.

I don't quite understand, do you mean that the phase shift could be a separate transform?

**Comment by bencottier** [comment]
Any preference for 2π inside or outside `period`? E.g. `sin((2π / P.period) .* x)` vs. `sin((1 / P.period) .* x)`?

Does this depend on whether the periodic function is sinusoidal or something else e.g. triangular wave?

**Comment by bencottier** [comment]
Not sure if this should be explicitly time-based. Should `period::Dates.Period`, `period::Real`, or either?

**Comment by glennmoy** [comment]
> Not sure if this should be explicitly time-based. Should `period::Dates.Period`, `period::Real`, or either?

No reason why it should be restricted to just `TimeType`s IMO - it might help to keep it flexible.

**Comment by glennmoy** [comment]
> Not sure if this should be explicitly time-based. Should `period::Dates.Period`, `period::Real`, or either?

I would say inside - check out our current code in FeatureEngineering for reference.

**Comment by glennmoy** [comment]
> > Note that phase_shift is not strictly necessary for this function from a feature engineering perspective but may be required for debugging purposes and/or comparison against our current use of this function.
> 
> I don't quite understand, do you mean that the phase shift could be a separate transform?

Check out the first issues in our FeatureEngineering package for more context.
