### ISSUE TITLE
Have `apply` return single column array when `cols` is a single column name

### ISSUE THREAD

**Issue by bencottier** [invenia/Transforms.jl#26]
The non-mutating `apply` in transformers.jl [always returns a vector](https://github.com/invenia/Transforms.jl/blob/83c8558aee22dbd343eceab659d132a80897c5fd/src/transformers.jl#L99) of the transformed columns specified in `cols`. `cols` is assumed to be a collection.

For convenience, we could add that if `cols` is a single column name we return the single column vector, rather than wrapping it in a 1-element vector.

I vote that we do the above using a bare String or Symbol (i.e. **not** in a collection), and still allow e.g. `cols=[:colname]` to return the 1-element vector. MWE of what this means:

```
julia> p = Power(3);

julia> df = DataFrame(:a => [1, 2, 3], :b => [4, 5, 6], :c => [7, 8, 9]);

julia> Transforms.apply(df, p; cols=[:a, :c])
2-element Array{Array{Int64,1},1}:
 [1, 8, 27]
 [343, 512, 729]

julia> Transforms.apply(df, p; cols=[:a])
1-element Array{Array{Int64,1},1}:
 [1, 8, 27]

julia> Transforms.apply(df, p; cols=:a)
3-element Array{Int64,1}:
  1
  8
 27
```

**Comment by glennmoy** [comment]
To avoid confusion can you elaborate on the issue description? maybe add a MWE of what you intend to implement?

**Comment by bencottier** [comment]
I added a MWE of what I'm advocating for.
