### ISSUE TITLE
Normalisation / Scaling transform

### ISSUE THREAD

**Issue by glennmoy** [invenia/Transforms.jl#3]
A transform that  scales data according to some distribution properties

Since this is a stateful transform, we may also want to apply reverse it later and/or apply the same scaling but to different data.

There might be a few ways to do this but one I'm considering is that the `Scaling` transform is parameterised by the type of Distribution we want to [`fit`](https://juliastats.org/Distributions.jl/latest/fit/#Distribution-Fitting) to the data?

MWE
```julia
x = rand(100)
y = rand(10)

# an uninitialised Scaling Transform
gaussian = Scaling{Normal}()

# scales x according to normal distribution and initialises `gaussian.d` with the mean/std of x
Transform.apply!(x, gaussian)  

# applies `gaussian` to `y` using stored mean/std
Transform.apply!(y, gaussian) 

# inverts the `gaussian` transform restoring `x` to original state
Transform.apply(x, gaussian; inverse=true)  
```

Something similar is kind of done in [StatsBase](https://juliastats.org/StatsBase.jl/stable/transformations/#) but only for `ZScore` and `UnitRange`

**Comment by bencottier** [comment]
I'm not clear on how Distributions relate, probably because I'm so used to mean-std scaling for everything.

More examples might help me understand. If we expect the data is log-normally distributed, would `Scaling{LogNormal}` apply the log function and then mean-std scaling? What about a uniform distribution - would that be (x - min(x)) / (max(x) - min(x))?

**Comment by rofinn** [comment]
Yeah, maybe an abstract `Scaling` type would make sense with specific implementations like `ZScore`, `MinMax`, etc would be better?

**Comment by bencottier** [comment]
Mean-std (`ZScore`) and min-max scaling (or more generally, linear scaling to some interval) are much more common than anything else, so that makes sense. Also, associating with Distributions might be confusing if we want to e.g. apply linear scaling even though the data looks normally distributed. We can always build more unusual scaling transforms beside, or around, these basic ones.

**Comment by bencottier** [comment]
I was trying to reuse [`ZScoreTransform`](https://juliastats.org/StatsBase.jl/stable/transformations/#StatsBase.fit-Tuple{Type{ZScoreTransform},AbstractArray{#s4,2}%20where%20#s4%3C:Real}) but it only works on `Matrix`.

**Comment by bencottier** [comment]
Should we support applying this over multiple table columns? That is it computes the scaling parameters over the matrix of concatenated columns, then applies that scaling to each.

**Comment by glennmoy** [comment]
> Should we support applying this over multiple table columns? That is it computes the scaling parameters over the matrix of concatenated columns, then applies that scaling to each.

Let's start simple and assume it only applies to one column at a time.

It introduces too many questions and complications to consider multiple columns right now...

**Comment by bencottier** [comment]
I was using `Statistics.mean(x; dims)` and `Statistics.std(x; dims)` like in `FeatureEngineering`, but I realised the notion of `dims` for that is opposite to `eachslice` which we have based things around. Example:

```
julia> M = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> mean(M; dims=1)
1×2 Array{Float64,2}:
 2.0  3.0

julia> mean(M; dims=2)
2×1 Array{Float64,2}:
 1.5
 3.5

julia> map(x -> mean(x), eachslice(M; dims=1))
2-element Array{Float64,1}:
 1.5
 3.5

julia> map(x -> mean(x), eachslice(M; dims=2))
2-element Array{Float64,1}:
 2.0
 3.0
```

The same goes for 3D arrays: `dims=1` for `eachslice` corresponds to `dims=[2, 3]` for `Statistics.mean`.

The `Statistics` functions keep the right shape for broadcasting so my plan is to still use them but invert the `dims` passed in.
