### ISSUE TITLE
One hot encoding transform

### ISSUE THREAD

**Issue by glennmoy** [invenia/Transforms.jl#7]
A one-hot-encoding transform for categorical variables

MWE
```julia
x = ["foo", "bar", "baz"]

ohe = OneHotEncoding()

Transform.apply(x, ohe)

# output
3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 0  0  1
```

**Comment by rofinn** [comment]
FWIW, if we're gonna change the type maybe we should use `Bool` for space efficiency?

```julia
julia> sizeof(true)
1

julia> sizeof(1)
8
```

That being said, maybe we could parameterize the type such that you state what you want returned? That way if I want to construct a pipeline where I know I'm gonna be merging the output from this type into an flattened array of floats then I'll construct it accordingly?
